### ISSUE TITLE
User's can have favourite blog posts.

### ISSUE THREAD

**Issue by Marceillo** [Marceillo/kayak-blog-pp4#10]
EPIC: User Interaction and Engagement

As a user, I want to favorite blog posts to find them later easily.

# Acceptance Criteria:

- Logged-in users can favorite/unfavorite posts.
- Favorite status is visually indicated on posts.
- Users have a page to view all their favorite posts.

# Tasks

- [ ] Add favorites field to Post model.
- [ ] Implement favorite/unfavorite functionality.
- [ ] Add a favorite button to post templates.
- [ ] Create a view for users to see their favorite posts.
- [ ] Create a template to display favorited posts.
