### ISSUE TITLE
Write blog posts as a content creator

### ISSUE THREAD

**Issue by Marceillo** [Marceillo/kayak-blog-pp4#3]
EPIC: Core Blog Functionality

As a **content creator**, I can **write blog posts ** so that **it is published**

# Acceptance Criteria:

- Logged-in content creators can access a create post page.
- Form includes fields for title, content, and publish status.
- Posts can be saved as drafts or published immediately.

# Tasks

- [x] Create PostForm
- [x] Implement CreatePostView
- [x] Create a template for post creation
- [x] Implement post-draft/publish functionality
- [x] Update post creation/edit template to include excerpt field
- [x] Implement automatic excerpt generation if left blank.
