### ISSUE TITLE
Upload images as a content creator  

### ISSUE THREAD

**Issue by Marceillo** [Marceillo/kayak-blog-pp4#4]
EPIC: Core Blog Functionality

As a **content creator**, I want to **upload** for **images for my blog posts **

# Acceptance Criteria:

- Image upload option in post-creation/edit form
- Images are displayed within blog posts

# Tasks

- [x] Add image field to Post model
- [x] Configure media settings in Django
- [x] Update post form to handle image uploads
- [x] Modify post templates to display images
