### ISSUE TITLE
User can edit and view their profile

### ISSUE THREAD

**Issue by Marceillo** [Marceillo/kayak-blog-pp4#6]
EPIC: User Authentication and Profiles

As a user, I want to view and edit my profile.

# Acceptance Criteria:

-Users have a profile page showing their information 
- Users can edit their profile information

# Tasks

- [x] Create UserProfile model
- [x] Implement profile view and edit view
- [x] Create templates for profile display and editing
