### ISSUE TITLE
Search for kayaking topics as a user

### ISSUE THREAD

**Issue by Marceillo** [Marceillo/kayak-blog-pp4#7]
EPIC: Core Blog Functionality

As a user, I want to search for specific kayaking topics.

# Acceptance Criteria:

The search or filter option is visible on all pages
Search returns relevant posts based on category or topic and content
Search results are paginated if there are many matches

# Tasks

- [ ] Implement search/filter functionality in views
- [ ] Create a search/filter results template
- [ ] Add search form/filter  to base template
