### ISSUE TITLE
A user can comment on blog post.

### ISSUE THREAD

**Issue by Marceillo** [Marceillo/kayak-blog-pp4#8]
EPIC: User Interaction and Engagement

As a user, I want to comment on blog posts.

# Acceptance Criteria:

- Logged-in users can leave comments on posts.
- Comments display the author's name and timestamp.

# Tasks

- [x] Create a Comment model.
- [x] Implement comment creation view.
- [x] Add comment form to post detail template.
- [x] Display comments on the post detail page.
