### ISSUE TITLE
User's can like blog posts

### ISSUE THREAD

**Issue by Marceillo** [Marceillo/kayak-blog-pp4#9]
EPIC: User Interaction and Engagement

 As a user, I want to like blog posts.

# Acceptance Criteria:

- Logged-in users can like/unlike posts.
- Like count is displayed on each post.
- The user's like status is visually indicated

# Tasks

- [ ] Create Like a model.
- [ ] Implement like/unlike functionality.
- [ ] Add like button and count to post templates.
- [ ] Use JavaScript for dynamic-like updates.
